config/routes.rb
Storehouse::Application.routes.draw do

  resources :bottles do
    get 'retire', :on => :member
  end
  

  resources :suppliers
  resources :locations
  resources :substances
  resources :sublocations  
  resources :logins, :only => [:new, :create]  
  
  match '/sublocation_select', :to => 'bottles#sublocation_select'
  match '/search',  :to => 'bottles#search'
  match '/login',   :to => 'logins#new'
  match '/logout',  :to => 'logins#destroy'
  match '/admin',   :to => 'pages#admin'
  
 root :to => 'bottles#new'
  

end

app/models/substance.rb
# == Schema Information
# Schema version: 20110315081343
#
# Table name: substances
#
#  id           :integer(38)     not null, primary key
#  name         :string(255)
#  created_at   :datetime
#  updated_at   :datetime
#  sort_keyword :string(255)
#

class Substance < ActiveRecord::Base
  # Callbacks
  before_save :create_sort_keyword

  has_many :bottles, :dependent => :destroy # If the substance is destroyed then all bottles with this substance are also destroyed

  validates :name,  :presence     => true

  def self.search(search, page_no)
    logger.debug "Search: #{search}"
    
    if search
      @substances = find(:all, :conditions => ['lower(name) LIKE ?', "%#{search.downcase}%"], :order => "LOWER(sort_keyword)").paginate(:page => page_no)
    else
      @substances = order("LOWER(sort_keyword)").paginate(:page => page_no)
    end
  end
  
  private
    def create_sort_keyword
      # Set a default sort keyword if the user didn't provide one
      self.sort_keyword = self.name.scan(/[A-Z]+[a-z]+/)[0] if self.sort_keyword.blank?
    end
  
end

app/controllers/substances_controller.rb
class SubstancesController < ApplicationController
  include ApplicationCommon::Security
  attr_reader :title, :subheading
  before_filter :is_admin

  def initialize
    super
    @title = "Substance"
  end

  def index
    @title = "Substances"
    @subheading = "List of substances"

    #@substances = Substance.search(params[:sublocation], params[:page])
    @substances = Substance.search(params[:search], params[:page])
    #@bottles = Bottle.search(params[:bottle], params[:page])
    
    if @substances.empty?
      flash.now[:error] = "Zero substances found."
      flash.now[:heading] = "Search result:"
    else
      session[:back_btn_path] = request.fullpath  
    end
  end

  def show
      @substance = Substance.find(params[:id])
      @subheading = @substance.name
  end  

  def new
    @substance = Substance.new
    @subheading = "New substance details"
  end

  def create
    @substance = Substance.new(params[:substance])
    if @substance.save
      flash[:heading] = "Substance admin:"
      flash[:notice] = "Substance created."
      redirect_to substances_path
    else
      @subheading = "New substance details"
      render :new 
    end
  end

  def edit
    @substance = Substance.find(params[:id])
    @subheading = "Edit: #{@substance.name}"
  end 

  def update
    @substance = Substance.find(params[:id])
    if @substance.update_attributes(params[:substance])
      flash[:heading] = "Substance admin:"
      flash[:notice] = "Substance updated."
      redirect_to substances_path
    else
      @title = "Edit Substance"
      render :edit
    end
  end

  def destroy
    Substance.destroy(params[:id])
    flash[:heading] = "Substance admin:"
    flash[:notice] = "Substance successfully deleted."
    redirect_to substances_path
  end

end

app/helpers/substances_helper.rb
module SubstancesHelper
end

app/views/substances/_form.html.erb
<%= f.error_messages :header_message => "Substance saving error", :message => "The substance could not be saved. Please correct the following:" %>
<div class="field">
	<%= f.label :name, :class => 'round' %>:&nbsp;<%= f.text_field :name %>
</div>
<div class="field">
	<%= f.label :sort_keyword, :class => 'round'%>:&nbsp;<%= f.text_field :sort_keyword %>
</div>

app/views/substances/_jquery_controls.html.erb
<script type="text/javascript" charset="utf-8">
	function other_setup(jQ) {
		jQ(function() {
			// Setup the buttons
			jQ("input:submit").button();
			jQ("#back_btn").button({
				icons: {
					primary:'ui-icon-arrow-1-w'
				}
			});
			
			// Set the default sort keyword
			jQ("#substance_name").change(function(){
				var sub_name = jQ("#substance_name").val();
				jQ("#substance_sort_keyword").val(sub_name.match(/[A-Z]+[a-z]+/));
			});
		});
	}
</script>

app/views/substances/_substance.html.erb
<li>
	<%= link_to substance.name, substance_path(substance), :class => "result_link" %><%= link_to "Delete", substance_path(substance), :method => :delete, :confirm => 'Deleting a substance will delete all bottles associated with that substance. Are you sure?', :class => "delete_btn" %><%= link_to "Edit", edit_substance_path(substance), :class => "edit_btn" %>
</li>

app/views/substances/edit.html.erb
<%= form_for(@substance) do |f| %>
	<%= render 'form', :f => f %>
	<div class="actions">
		<%= link_to "Back to list", session[:back_btn_path], :id => "back_btn" %>
		<%= f.submit "Update" %>
	</div>
<% end %>

<%= render 'jquery_controls' %>

app/views/substances/index.html.erb
<%= link_to "Create new Substance", new_substance_path, :id => "create_btn" %>
<%= form_tag(substances_path, {:class => "round", :method => :get, :id => "search_box"}) do %>
  <%= text_field_tag :search, params[:search] %><%= submit_tag "Search", :name => nil -%>
<% end -%>
<div class="round" id="result_list">
<%= will_paginate %>
<ul>
<%= render @substances %>
</ul>
<%= will_paginate %>

</div>
<script type="text/javascript" charset="utf-8">
	function other_setup(jQ) {
		jQ(function() {
			// Setup the buttons
			jQ("#create_btn, input:submit").button();
			jQ(".edit_btn").button({
				icons: {
					primary:'ui-icon-pencil'
				}
			});
			jQ(".delete_btn").button({
				icons: {
					primary:'ui-icon-trash'
				},
				text: false
			});
			
			jQ("#result_list li:odd").addClass("li_odd");
		});
	}
</script>

app/views/substances/new.html.erb
<%= form_for(@substance) do |f| %>
	<%= render 'form', :f => f %>
  	<div class="actions">
		<%= link_to "Back to list", session[:back_btn_path], :id => "back_btn" %>
		<%= f.submit "Create substance" %>
  	</div>
<% end %>

<%= render 'jquery_controls' %>

app/views/substances/show.html.erb
<div class="field">
  <%= content_tag :label, "Name", :class => 'round' %>:&nbsp;<%= @substance.name %>
</div>
<div class="field">
  <%= content_tag :label, "Sort keyword", :class => 'round' %>:&nbsp;<%= @substance.sort_keyword %>
</div>
<div class="actions">
	<%= link_to "Back to list", session[:back_btn_path], :id => "back_btn" %>
</div>

<script type="text/javascript" charset="utf-8">
	function other_setup(jQ) {
		jQ(function() {
			// Setup the buttons
			jQ("#back_btn").button({
				icons: {
					primary:'ui-icon-arrow-1-w'
				}
			});
		});
	}
</script>