config/routes.rb
Storehouse::Application.routes.draw do

  resources :bottles do
    get 'retire', :on => :member
  end
  

  resources :suppliers
  resources :locations
  resources :substances
  resources :sublocations  
  resources :logins, :only => [:new, :create]  
  
  match '/sublocation_select', :to => 'bottles#sublocation_select'
  match '/search',  :to => 'bottles#search'
  match '/login',   :to => 'logins#new'
  match '/logout',  :to => 'logins#destroy'
  match '/admin',   :to => 'pages#admin'
  
 root :to => 'bottles#new'
  

end

app/models/bottle.rb
# == Schema Information
# Schema version: 20110603071421
#
# Table name: bottles
#
#  id             :integer(38)     not null, primary key
#  supplier_id    :integer(38)
#  substance_id   :integer(38)
#  size           :integer(38)
#  unit_id        :integer(38)
#  po_number      :string(255)
#  group_id       :integer(38)
#  date_received  :date
#  created_at     :datetime
#  updated_at     :datetime
#  cas_number     :string(255)
#  sublocation_id :integer(38)
#  product_cat_no :integer(38)
#  retired_at     :datetime
#  flammable      :boolean(1)
#  hazardous      :boolean(1)
#  barcode        :string(255)
#

class Bottle < ActiveRecord::Base
  attr_accessor :quantity
  attr_accessor :location_id
  attr_accessor :sublocation_new
  @loc_id # See the overriden attr_accessor methods for location_id for the purpose of this object variable
  @retired # Internal variable mostly used for search
  
  # Callbacks
  after_initialize :default_values
  before_save :create_any_new_sublocation
  
  # Association is belongs_to if object references an already existing object.  Assoc'n is has_a if referenced object is created at the same time, ie: account has_a account_history
  belongs_to :supplier
  belongs_to :substance
  belongs_to :unit
#  belongs_to :location # remove later as a sublocation links to a location
  belongs_to :sublocation
  belongs_to :group
  
  validates_presence_of :cas_number
  validates_presence_of :supplier_id
  validates_presence_of :substance_id
  validates_numericality_of :size, :greater_than => 0
  validates_presence_of :unit_id, :message => "of size not selected"
  # Only validate quantity if the bottle is new, ie has no id, as quantity is only used to create new bottles
  validates_numericality_of :quantity, :greater_than => 0, :integer_only => true, :if => "id.nil?"
  validates_presence_of :location_id
  # A sublocation must be chosen of the name of a new location supplied
  validates_presence_of :sublocation_id, :if => "sublocation_new.blank?", :message => "must be chosen from the list or a new sub-location for this location entered" 
#  validates_presence_of :sublocation_new, :if => "sublocation_id.nil?"
  validates_presence_of :po_number
  validates_presence_of :group_id

  def self.search(search, page_no, substance_name)
    search = clean_hash(search)
    
    if !search.empty? || !substance_name.empty?
      search_clause = ""
#      values_array = Array.new
      values_hash = Hash.new

      # Handle 'retired'
      if search.has_key?(:retired)
        search_clause = search[:retired] == "1" ? "retired_at is not null and " : "retired_at is null and "
        search.delete(:retired)
      end
      
      if !substance_name.empty?
        substance = Substance.find_by_name(substance_name)
        search[:substance_id] = substance.id if !substance.nil?
        
      end
      
      search.each { |key, value|
#        search_clause << "#{key} = ? and "
        search_clause << "#{key} = :#{key} and "
#        values_array << value
        values_hash[key.to_sym] = value
      }
      
      search_clause = search_clause.chomp(" and ")
      
      logger.debug "search_clause: #{search_clause}"  
      logger.debug "values_hash: #{values_hash.to_s}"  
      
      @bottles = includes(:supplier, :substance, :group).where(search_clause, values_hash).order("substances.name ASC, suppliers.name ASC, groups.name ASC").paginate(:page => page_no)
    else
      @bottles = includes(:supplier, :substance, :group).order("substances.name ASC, suppliers.name ASC, groups.name ASC").paginate(:page => page_no)
    end
  end
  
  def save_batch
    if self.valid?
      self.save
      (self.quantity.to_i - 1).times {
        if !self.clone.save
          return false
        end
      }
      return true
    end
    return false
  end
  
  def location_id # Override the default attr_accessor getter method 
    return self.sublocation.nil? ? @loc_id : self.sublocation.location_id
  end
  
  def location_id=(loc_id) # Override the default attr_accessor setter method as an intermediate location_id store is needed to prevent self referencing endless stack loop in getter method
      @loc_id = loc_id #set the contents of loc_id to loc_id  
  end
  
  def retired? 
    # If the date of the retirement is blank then retired = false , unless retired was set to true in the case of search.  The main use of 'retired' is as a search form variable, not as a true bottle attribute
    if !self.retired_at.blank?
      true
    else
      @retired.blank? ? false : @retired
    end
  end
  
  def retired=(status)
    @retired = status
  end
  
  def retire()
    self.retired_at = DateTime.now
    self.save
  end
  
  def assign_substance(substance_name)
    if !substance_name.empty?
      self.substance = Substance.find_by_name(substance_name)
      if self.substance.nil?
        self.substance = Substance.create(:name => substance_name)
      end
    else
      self.substance = nil
    end
  end
  
  private
    def default_values
      if new_record?
        self.date_received ||= Date.current
        self.retired = false
      end
    end
    
    def create_any_new_sublocation
      if !self.sublocation_new.blank? #&& self.sublocation.nil?
        self.sublocation = Sublocation.create(:name => self.sublocation_new, :location_id => self.location_id)
        self.sublocation_new = nil
      end
    end
    
    def self.clean_hash(search)
      # Remove blank search terms
      search.delete_if { |key, value| value.blank? }
      
      if search.length == 1 && search.has_key?(:retired)
        # Then there must only be one clause, retired. If it is blank (unchecked) then might as well remove it as well because it means the whole search form was blank.
        search.delete(:retired) if search[:retired] == "0"
      end
      
      return search
    end
end

app/controllers/bottles_controller.rb
class BottlesController < ApplicationController
    include ActionView::Helpers::TextHelper
    attr_reader :title, :subheading

    def initialize
      super
      @title = "Bottle"
    end

    def index
      @title = "Bottles"
      @subheading = "List of bottles"

      @bottles = Bottle.search(params[:bottle], params[:page], params[:substance])
      if @bottles.empty?
        flash.now[:error] = "Zero results found."
        flash.now[:heading] = "Search result:"
      else
        session[:back_btn_path] = request.fullpath
      end
    end

    def show
        @bottle = Bottle.includes(:supplier, :substance, :unit, :sublocation, :group).find(params[:id])
        @subheading = "Bottle: #{@bottle.id}, #{@bottle.substance.name}"
    end  

    def new
      @bottle = Bottle.new 
      @subheading = "New bottle details"
      @sublocations = Array.new # An empty collection because not location has be chosen yet
    end

    def create
      @bottle = Bottle.new(params[:bottle])
      @bottle.assign_substance(params[:substance])
      
      if @bottle.valid?
        @bottle.save_batch
        flash[:heading] = "Bottle management:"
        flash[:notice] = "#{pluralize( @bottle.quantity.to_i, 'Bottle' )} created."
        redirect_to new_bottle_path
      else
        @subheading = "New bottle details"
        @sublocations = Sublocation.find_all_by_location_id(@bottle.location_id, :order => :name)
        render :new 
      end
    end

    def edit
      @bottle = Bottle.find(params[:id])
      @subheading = "Edit: bottle #{@bottle.id}"
      @sublocations = Sublocation.find_all_by_location_id(@bottle.sublocation.location, :order => :name)
    end 

    def update
      @bottle = Bottle.find(params[:id])
      @bottle.assign_substance(params[:substance])
      
      if @bottle.update_attributes(params[:bottle])
        flash[:heading] = "Bottle management:"
        flash[:notice] = "Bottle updated."
        redirect_to new_bottle_path
      else
        @title = "Edit Bottle"
        @sublocations = Sublocation.find_all_by_location_id(@bottle.location_id, :order => :name)
        render :edit
      end
    end

    def destroy
      Bottle.find(params[:id]).destroy
      flash[:heading] = "Bottle management:"
      flash[:notice] = "Bottle successfully deleted."
      redirect_to new_bottle_path
    end
    
    def search
      @bottle = Bottle.new
      @bottle.date_received = nil
      @subheading = "Search for bottle"
    end
    
    def sublocation_select
      @sublocations = Sublocation.find_all_by_location_id(params[:location_id], :order => :name)
      render :layout => false
    end
    
    def retire
      Bottle.find(params[:id]).retire
      flash[:heading] = "Bottle management:"
      flash[:notice] = "Bottle successfully retired."
      redirect_to new_bottle_path
    end

end

app/helpers/bottles_helper.rb
module BottlesHelper

  def quantity_field(f, id, uri)
    # If this is a new bottle with no id and we are not on the search page the display the quantity field
    if id.blank? && (uri =~ /search/).nil?
      return "<div class='field'>#{f.label :quantity, :class => 'round'}:&nbsp;#{f.text_field :quantity}</div>"
    end
  end
  
  def date_received_field(f, id, uri, date_field)
    if id.blank?
      return "<div class='field'>#{f.label :date_received, :class => 'round'}:&nbsp;#{f.text_field(:date_received)}</div>"
    else
      return "<div class='field'>#{f.label :date_received, :class => 'round'}:&nbsp;#{date_field}</div>"
    end
  end
  
  def date_retired_at(date_field)
    return date_field.blank? ? "" : date_field.strftime("%Y-%m-%d")
  end
  
  def substance_input(bottle)
    if bottle.errors[:substance_id].empty?
      return content_tag(:span, text_field_tag(:substance, bottle.substance.nil? ? '' : bottle.substance.name), :class => 'ui-widget')
    else
      return content_tag(:div, content_tag(:span, text_field_tag(:substance, bottle.substance.nil? ? '' : bottle.substance.name), :class => 'ui-widget'), :class=> 'field_with_errors')
    end
  end
end

app/views/bottles/_bottle.html.erb
<li>
	<%= link_to "#{bottle.substance.name}, #{bottle.supplier.name}", bottle_path(bottle), :class => "result_link" %><%= link_to("Retire", retire_bottle_path(bottle), :confirm => 'Are you sure?', :class => "delete_btn") if !bottle.retired? %><%= link_to "Edit", edit_bottle_path(bottle), :class => "edit_btn" %>
</li>

app/views/bottles/_form.html.erb
<% 
#  supplier_id    :integer(38)
#  substance_id   :integer(38)
#  size           :integer(38)
#  unit_id        :integer(38)
#  po_number      :string(255)
#  group_id       :integer(38)
#  date_received  :date
#  created_at     :datetime
#  updated_at     :datetime
#  cas_number     :string(255)
#  sublocation_id :integer(38)
#  product_cat_no :integer(38)

# ====== > > rails plugin install git://github.com/rails/dynamic_form.git for displaying errors in the next line
 -%>
<%= f.error_messages :header_message => "Bottle saving error", :message => "The bottle could not be saved. Please correct the following:" %>
<div class="field">
  	<%= f.label :cas_number, "CAS number", :class => 'round' %>:&nbsp;<%= f.text_field :cas_number %>
</div>
<div class="field">
  	<%= f.label :barcode, :class => 'round' %>:&nbsp;<%= f.text_field :barcode %>
</div>
<div class=" field">
	<%= f.label :substance_id, :class => 'round' %>:&nbsp;<%= substance_input(@bottle) %>
</div>
<div class="field">
  	<%= f.label :supplier_id, :class => 'round' %>:&nbsp;<%= select(:bottle, :supplier_id, Supplier.order(:name).collect {|sup| [ sup.name, sup.id ] }, { :include_blank => true }) %>
</div>
<div class="field">
  	<%= f.label :product_cat_no, "Product cat No.", :class => 'round' %>:&nbsp;<%= f.text_field :product_cat_no %>
</div>
<div class="field">
  <%= f.label :flammable, :class => 'round' %>:&nbsp;<%= f.check_box :flammable %>
</div>
<div class="field">
  <%= f.label :hazardous, :class => 'round' %>:&nbsp;<%= f.check_box :hazardous %>
</div>
<div class="field">
  	<%= f.label :size, :class => 'round' %>:&nbsp;<%= f.text_field :size %>&nbsp;<%= select(:bottle, :unit_id, Unit.order(:name).collect {|un| [ un.name, un.id ] }, { :include_blank => true }) %>
</div>
<%= raw(quantity_field(f, @bottle.id, request.fullpath)) %>
<div class="field">
  	<%= f.label :location_id, :class => 'round' %>:&nbsp;<%= select(:bottle,:location_id, Location.order(:name).collect {|loc| [ loc.name, loc.id ] }, { :include_blank => true }) %>
</div>
<div class="field">
	<%= f.label :sublocation_id, "Sub-location", :class => 'round' %>:&nbsp;<span id="sublocations_container"><%= collection_select(:bottle, :sublocation_id, @sublocations, :id, :name, { :include_blank => true }) %></span>
  	<%= f.text_field :sublocation_new, :size => 20 %>
</div>
<div class="field">
  	<%= f.label :po_number, "PO number", :class => 'round' %>:&nbsp;<%= f.text_field :po_number %>
</div>
<div class="field">
  	<%= f.label :group_id, :class => 'round' %>:&nbsp;<%= select(:bottle, :group_id, Group.order(:name).collect {|grp| [ grp.name, grp.id ] }, { :include_blank => true }) %>
</div>
<%= raw(date_received_field(f, @bottle.id, request.fullpath, @bottle.date_received)) %>
<div class="field">
	<%= f.label :retired_at, "Date retired", :class => 'round' %>:&nbsp;<%= date_retired_at(@bottle.retired_at) %>
</div>

app/views/bottles/_form_search.html.erb
<% 
#  cas_number    :string(255)
#  substance_id  :integer
#  supplier_id   :integer
#  size          :decimal(, )
#  product_cat_no:integer
#  po_number     :string(255)
#  retired?      :boolean

# ====== > > rails plugin install git://github.com/rails/dynamic_form.git for displaying errors in the next line
 -%>
<%= f.error_messages :header_message => "Bottle saving error", :message => "The bottle could not be saved. Please correct the following:" %>
<div class="field">
  <%= f.label :cas_number, "CAS number", :class => 'round' %>:&nbsp;<%= f.text_field :cas_number %>
</div>
<div class="field">
  	<%= f.label :barcode, :class => 'round' %>:&nbsp;<%= f.text_field :barcode %>
</div>
<!--
<div class="field">
  <%= f.label :substance_id, :class => 'round' %>:&nbsp;<%= select(:bottle, :substance_id, Substance.order(:sort_keyword).collect {|sub| [ sub.name, sub.id ] }, { :include_blank => true }) %>
</div>
-->
<div class=" field">
	<%= f.label :substance_id, :class => 'round' %>:&nbsp;<%= substance_input(@bottle) %>
</div>
<div class="field">
  <%= f.label :supplier_id, :class => 'round' %>:&nbsp;<%= select(:bottle, :supplier_id, Supplier.order(:name).collect {|sup| [ sup.name, sup.id ] }, { :include_blank => true }) %>
</div>
<div class="field">
  	<%= f.label :product_cat_no, "Product cat No.", :class => 'round' %>:&nbsp;<%= f.text_field :product_cat_no %>
</div>
<div class="field">
  <%= f.label :po_number, "PO number", :class => 'round' %>:&nbsp;<%= f.text_field :po_number %>
</div>
<div class="field">
  <%= f.label :retired, :class => 'round' %>:&nbsp;<%= f.check_box :retired? %>
</div>

app/views/bottles/_jquery_controls.html.erb
<script type="text/javascript" charset="utf-8">
	function other_setup(jQ) {
		jQ(function() {
			// Setup the buttons
			jQ("input:submit").button();
			jQ("#back_btn").button({
				icons: {
					primary:'ui-icon-arrow-1-w'
				}
			});
			jQ("#bottle_date_received").datepicker({ dateFormat: 'yy-mm-dd' });
			
			// Setup event code
			jQ('#bottle_location_id').change(function(){
				//alert("location_id: " + jQ(this).val());
				//var loc_id = jQ(this).val();
				jQ.post('<%= sublocation_select_path %>', { location_id: jQ(this).val() }, function(data){
					jQ("#sublocations_container").html(data);
					wire_up_sublocation(jQ);
				});
			});

			// Can choose search with CAS number or Substance selection but not both.  If one is indicated then blank the other.
			function wire_up_sublocation(jQ) {
				jQ('#bottle_sublocation_id').change(function(){
					if(jQ('#bottle_sublocation_id option:selected').text() != '') {
						jQ('#bottle_sublocation_new').val('');
					}
				});
			}
			
			wire_up_sublocation(jQ);
			
			jQ('#bottle_sublocation_new').change(function(){
				if(jQ(this).val() != '') {
					jQ('#bottle_sublocation_id').val(0);
				}
			});
			
			var substances = <%= raw Substance.order(:sort_keyword).collect {|sub| sub.name }.to_json %>;
			jQ("#substance").autocomplete({
				source: substances
			});
		});
	}
</script>

app/views/bottles/edit.html.erb
<%= form_for(@bottle) do |f| %>
	<%= render 'form', :f => f %>
	<div class="actions">
		<%= link_to "Back to list", session[:back_btn_path], :id => "back_btn" %>
		<%= f.submit "Update" %>
	</div>
<% end %>

<%= render 'jquery_controls' %>

app/views/bottles/index.html.erb
<%= link_to "Create new Bottle", new_bottle_path, :id => "create_btn" %>
<div class="round" id="result_list">
<%= will_paginate %>
<ul>
<%= render @bottles %>
</ul>
<%= will_paginate %>

</div>
<script type="text/javascript" charset="utf-8">
	function other_setup(jQ) {
		jQ(function() {
			// Setup the buttons
			jQ("#create_btn, input:submit").button();
			jQ(".edit_btn").button({
				icons: {
					primary:'ui-icon-pencil'
				}
			});
			jQ(".delete_btn").button({
				icons: {
					primary:'ui-icon-trash'
				},
				text: false
			});
			
			jQ("#result_list li:odd").addClass("li_odd");
		});
	}
</script>

app/views/bottles/new.html.erb
<%= form_for(@bottle) do |f| %>
	<%= render 'form', :f => f %>
  	<div class="actions">
		<%= f.submit "Create bottle" %>
		<p id="out"></p>
  	</div>
<% end %>

<%= render 'jquery_controls' %>

app/views/bottles/search.html.erb
<%= form_for(@bottle, :url => bottles_path, :html => {:method => :get} ) do |f| %>
	<%= render 'form_search', :f => f %>
  	<div class="actions">
		<%= f.submit "Search", :name => nil %>
  	</div>
<% end %>

<script type="text/javascript" charset="utf-8">
	function other_setup(jQ) {
		jQ(function() {
			// Setup the buttons
			jQ('input:submit').button();
			jQ('#bottle_date_received').datepicker({ dateFormat: 'yy-mm-dd' });
			
			// Setup event code
			// Can choose search with CAS number or Substance selection but not both.  If one is indicated then blank the other.
			jQ('#bottle_substance_id').change(function(){
				if(jQ('#bottle_substance_id option:selected').text() != '') {
					jQ('#bottle_cas_number').val('');
				}
			});
			
			jQ('#bottle_cas_number').change(function(){
				if(jQ(this).val() != '') {
					jQ('#bottle_substance_id').val(0);
				}
			});
			
			var substances = <%= raw Substance.order(:sort_keyword).collect {|sub| sub.name }.to_json %>;
			jQ("#substance").autocomplete({
				source: substances
			});
		});
	}
</script>

app/views/bottles/show.html.erb
<div class="field">
  <%= content_tag :label, "CAS number", :class => 'round' %>:&nbsp;<%= @bottle.cas_number %>
</div>
<div class="field">
  <%= content_tag :label, "Barcode", :class => 'round' %>:&nbsp;<%= @bottle.barcode %>
</div>
<div class="field">
  <%= content_tag :label, "Substance", :class => 'round' %>:&nbsp;<%= @bottle.substance.name %>
</div>
<div class="field">
  <%= content_tag :label, "Supplier", :class => 'round' %>:&nbsp;<%= @bottle.supplier.name %>
</div>
<div class="field">
  <%= content_tag :label, "Product cat No.", :class => 'round' %>:&nbsp;<%= @bottle.product_cat_no %>
</div>
<div class="field">
  <%= content_tag :label, "Flammable", :class => 'round' %>:&nbsp;<%= @bottle.flammable ? image_tag("tick.png") : raw("&nbsp;") %>
</div>
<div class="field">
  <%= content_tag :label, "Hazardous", :class => 'round' %>:&nbsp;<%= @bottle.hazardous ? image_tag("tick.png") : raw("&nbsp;") %>
</div>
<div class="field">
  <%= content_tag :label, "Size", :class => 'round' %>:&nbsp;<%= "#{@bottle.size} #{@bottle.unit.name}" %>
</div>
<div class="field">
  <%= content_tag :label, "Location", :class => 'round' %>:&nbsp;<%= @bottle.sublocation.location.name %>
</div>
<div class="field">
  <%= content_tag :label, "Sub-location", :class => 'round' %>:&nbsp;<%= @bottle.sublocation.name %>
</div>
<div class="field">
  <%= content_tag :label, "PO number", :class => 'round' %>:&nbsp;<%= @bottle.po_number %>
</div>
<div class="field">
  <%= content_tag :label, "Group", :class => 'round' %>:&nbsp;<%= @bottle.group.name %>
</div>
<div class="field">
  <%= content_tag :label, "Date received", :class => 'round' %>:&nbsp;<%= @bottle.date_received %>
</div>
<div class="field">
  <%= content_tag :label, "Date retired", :class => 'round' %>:&nbsp;<%= date_retired_at(@bottle.retired_at) %>
</div>

<div class="actions">
	<%= link_to "Back to list", session[:back_btn_path], :id => "back_btn" %>
</div>
<script type="text/javascript" charset="utf-8">
	function other_setup(jQ) {
		jQ(function() {
			// Setup the buttons
			jQ("#back_btn").button({
				icons: {
					primary:'ui-icon-arrow-1-w'
				}
			});
		});
	}
</script>

app/views/bottles/sublocation_select.html.erb
<%= collection_select(:bottle, :sublocation_id, @sublocations, :id, :name, { :include_blank => true }) -%>