config/routes.rb
Storehouse::Application.routes.draw do

  resources :bottles do
    get 'retire', :on => :member
  end
  

  resources :suppliers
  resources :locations
  resources :substances
  resources :sublocations  
  resources :logins, :only => [:new, :create]  
  
  match '/sublocation_select', :to => 'bottles#sublocation_select'
  match '/search',  :to => 'bottles#search'
  match '/login',   :to => 'logins#new'
  match '/logout',  :to => 'logins#destroy'
  match '/admin',   :to => 'pages#admin'
  
 root :to => 'bottles#new'
  

end

app/models/sublocation.rb
# == Schema Information
# Schema version: 20110314031400
#
# Table name: sublocations
#
#  id          :integer(38)     not null, primary key
#  name        :string(255)
#  location_id :integer(38)
#  created_at  :datetime
#  updated_at  :datetime
#

class Sublocation < ActiveRecord::Base
  belongs_to :location
  has_many :bottles, :dependent => :destroy # If the sublocation is destroyed then all bottles with this location are also destroyed
  
  validates             :name,  :presence     => true,
                                :length       => { :within => 3..40 }
  validates_presence_of :location_id
                    
  def self.search(search, page_no)
    if !search.nil?
      search = nil if search[:location_id].blank? 
    end
    
    if search 
      @sublocations = includes(:location).where(search).order("LOWER(locations.name) ASC, LOWER(sublocations.name) ASC").paginate(:page => page_no)
    else
      @sublocations = includes(:location).order("LOWER(locations.name) ASC, LOWER(sublocations.name) ASC").paginate(:page => page_no)
    end
  end
  
end

app/controllers/sublocations_controller.rb
class SublocationsController < ApplicationController
  include ApplicationCommon::Security
  attr_reader :title, :subheading
  before_filter :is_admin

  def initialize
    super
    @title = "Sub-location"
  end

  def index
    @title = "Sub-locations"
    @subheading = "List of sub-locations"
    @sublocation = Sublocation.new(params[:sublocation]) # This is to set the location select box with the currently selected sublocation.location_id 
    @sublocations = Sublocation.search(params[:sublocation], params[:page])
    if @sublocations.empty?
      flash.now[:error] = "Zero sub-locations found."
      flash.now[:heading] = "Search result:"
    else
      session[:back_btn_path] = request.fullpath
    end
  end

  def show
      @sublocation = Sublocation.find(params[:id])
      @subheading = @sublocation.name
  end  

  def new
    @sublocation = Sublocation.new
    @subheading = "New sub-location details"
  end

  def create
    @sublocation = Sublocation.new(params[:sublocation])
    if @sublocation.save
      flash[:heading] = "Sub-location admin:"
      flash[:notice] = "Sub-location created."
      redirect_to sublocations_path
    else
      @subheading = "New sub-location details"
      render :new 
    end
  end

  def edit
    @sublocation = Sublocation.find(params[:id])
    @subheading = "Edit: #{@sublocation.name}"
  end 

  def update
    @sublocation = Sublocation.find(params[:id])
    if @sublocation.update_attributes(params[:sublocation])
      flash[:heading] = "Sub-location admin:"
      flash[:notice] = "Sub-location updated."
      redirect_to sublocations_path
    else
      @title = "Edit Sub-location"
      render :edit
    end
  end

  def destroy
    Sublocation.find(params[:id]).destroy
    flash[:heading] = "Sub-location admin:"
    flash[:notice] = "Sub-location successfully deleted."
    redirect_to sublocations_path
  end

end

app/views/sublocations/_form.html.erb
<%= f.error_messages :header_message => "Sublocation saving error", :message => "The sublocation could not be saved. Please correct the following:" %>
<div class="field">
  <%= f.label :name, :class => 'round' %>:&nbsp;<%= f.text_field :name %>
</div>
<div class="field">
  	<%= f.label :location_id, :class => 'round' %>:&nbsp;<%= select(:sublocation, :location_id, Location.order(:name).collect {|loc| [ loc.name, loc.id ] }, { :include_blank => true }) %>
</div>

app/views/sublocations/_sublocation.html.erb
<li>
	<%= link_to "#{sublocation.location.name}, #{sublocation.name}", sublocation_path(sublocation), :class => "result_link" %><%= link_to "Delete", sublocation_path(sublocation), :method => :delete, :confirm => 'Deleting a sub-location will delete all bottles associated with that sub-location. Are you sure?', :class => "delete_btn" %><%= link_to "Edit", edit_sublocation_path(sublocation), :class => "edit_btn" %>
</li>

app/views/sublocations/edit.html.erb
<%= form_for(@sublocation) do |f| %>
	<%= render 'form', :f => f %>
	<div class="actions">
		<%= link_to "Back to list", session[:back_btn_path], :id => "back_btn" %>
		<%= f.submit "Update" %>
	</div>
<% end %>

<script type="text/javascript" charset="utf-8">
	function other_setup(jQ) {
		jQ(function() {
			// Setup the buttons
			jQ("input:submit").button();
			jQ("#back_btn").button({
				icons: {
					primary:'ui-icon-arrow-1-w'
				}
			});
		});
	}
</script>

app/views/sublocations/index.html.erb
<%= link_to "Create new Sub-location", new_sublocation_path, :id => "create_btn" %>
<%= form_for(@sublocation, :url => sublocations_path, :html => {:class => "round", :method => :get, :id => "search_box_subloc"} ) do |f| %>
	<%= f.label "At location", :class => 'round' %>:&nbsp;<%= select(:sublocation, :location_id, Location.order(:name).collect {|loc| [ loc.name, loc.id ] }, { :include_blank => true }) %>
	<%= f.submit "Search", :name => nil %>
<% end -%>
<div class="round" id="result_list">
<%= will_paginate %>
<ul>
<%= render @sublocations %>
</ul>
<%= will_paginate %>

</div>
<script type="text/javascript" charset="utf-8">
	function other_setup(jQ) {
		jQ(function() {
			// Setup the buttons
			jQ("#create_btn, input:submit").button();
			jQ(".edit_btn").button({
				icons: {
					primary:'ui-icon-pencil'
				}
			});
			jQ(".delete_btn").button({
				icons: {
					primary:'ui-icon-trash'
				},
				text: false
			});
			
			jQ("#result_list li:odd").addClass("li_odd");
		});
	}
</script>

app/views/sublocations/new.html.erb
<%= form_for(@sublocation) do |f| %>
	<%= render 'form', :f => f %>
  	<div class="actions">
		<%= link_to "Back to list", session[:back_btn_path], :id => "back_btn" %>
		<%= f.submit "Create sub-location" %>
  	</div>
<% end %>

<script type="text/javascript" charset="utf-8">
	function other_setup(jQ) {
		jQ(function() {
			// Setup the buttons
			jQ("input:submit").button();
			jQ("#back_btn").button({
				icons: {
					primary:'ui-icon-arrow-1-w'
				}
			});
		});
	}
</script>

app/views/sublocations/show.html.erb
<div class="field">
  <%= content_tag :label, "Name", :class => 'round' %>:&nbsp;<%= @sublocation.name %>
</div>
<div class="field">
  <%= content_tag :label, "Location", :class => 'round' %>:&nbsp;<%= @sublocation.location.name %>
</div>
<div class="actions">
	<%= link_to "Back to list", session[:back_btn_path], :id => "back_btn" %>
</div>
<script type="text/javascript" charset="utf-8">
	function other_setup(jQ) {
		jQ(function() {
			// Setup the buttons
			jQ("#back_btn").button({
				icons: {
					primary:'ui-icon-arrow-1-w'
				}
			});
		});
	}
</script>