config/routes.rb
Storehouse::Application.routes.draw do

  resources :bottles do
    get 'retire', :on => :member
  end
  

  resources :suppliers
  resources :locations
  resources :substances
  resources :sublocations  
  resources :logins, :only => [:new, :create]  
  
  match '/sublocation_select', :to => 'bottles#sublocation_select'
  match '/search',  :to => 'bottles#search'
  match '/login',   :to => 'logins#new'
  match '/logout',  :to => 'logins#destroy'
  match '/admin',   :to => 'pages#admin'
  
 root :to => 'bottles#new'
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= stylesheet_link_tag :all %>
  <%= stylesheet_link_tag "jquery/jquery-ui-1.8.9.custom" %>
  <% # this conflicts with jquery under IE8 so was removed in favour of the specific JS includes below: = javascript_include_tag :defaults %>
  <%= javascript_include_tag "prototype.js" %>
  <%= javascript_include_tag "application.js" %>
  <%= javascript_include_tag "rails.js" %>
  <%= javascript_include_tag "jquery/jquery-1.4.4.js" %>
  <%= javascript_include_tag "jquery/jquery-ui-1.8.9.custom.min.js" %>
  <%= csrf_meta_tag %>
</head>
<body>	
	<div id="main">
		<div id="menu_top">
			<%= image_tag "logo.png", :title => "logo", :id => "logo" -%>
			<%= image_tag "storehouse.png", :title => "storehouse", :id => "storehouse" -%>
			<ul>
				<li><%= link_to image_tag("menu/logout.png", :title => "logout"), logout_path %></li>
				<li><%= link_to image_tag("menu/admin.png", :title => "admin"), admin_path, :class => "menu_item" %></li>
				<li><%= link_to image_tag("menu/search.png", :title => "search"), search_path, :class => "menu_item" %></li>
				<li><%= link_to image_tag("menu/receive.png", :title => "receive chemical"), new_bottle_path, :class => "menu_item" %></li>
			</ul>
			<div class="clear_all"></div>
		</div>
		<div id="content" class="round">
			<h1><%= heading %></h1>
			<div id="inner_spacer">
				<hr />
				<h2><%= subheading %></h2>
				<hr />
				<div class="round" id="inner_content">
					<%= flash_message(flash)%>
					<%= yield %>
				</div>
				<hr />
			</div>
			<% # = debug(params) if Rails.env.development? %>
		</div>
		<%= image_tag "barcode_vert.png", :title => "vertical_barcode", :id => "barcode_vert" %>
		<p class="clear_all"></p>
	</div>
	<script type="text/javascript" charset="utf-8">
		jQuery.noConflict();
		// This code is necessary because under Rails >304 when Rails was receiving an AJAX request, the csrf-token didn't match and it was resetting the session - causing login session info to be lost after an AJAX call.
		jQuery.ajaxSetup({
		  beforeSend: function(xhr) {
		    xhr.setRequestHeader('X-CSRF-Token', jQuery('meta[name="csrf-token"]').attr('content'));
		  }
		});
		jQuery(document).ready(function() {
			// Fade out flash_info if found
			jQuery("#flash_info").delay(3500).animate({
			    height: 'hide',
			    opacity: 'hide'
			}, 'slow');
			
			if (window.other_setup) {
				other_setup(jQuery); // other_setup is an optional javascript function that may be in partials or views and that will be called if it exists.
			}
	 });
	</script>
</body>
</html>